improv kopi func and update litegapps cotroller

diff --git a/etc/litegapps_utils/kopi b/etc/litegapps_utils/kopi
--- a/etc/litegapps_utils/kopi
+++ b/etc/litegapps_utils/kopi
@@ -3,9 +3,7 @@
 ####################################
 #          By : wahyu6070          #
 ####################################
-print(){
-	ui_print "$1"
-	}
+print(){ $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> $OUTFD; }
 	
 printlog(){
 	print "$1"
@@ -120,7 +118,6 @@ setime(){
     fi
 }
 
-
 bash_color(){
 G='\e[01;32m'		# GREEN TEXT
 R='\e[01;31m'		# RED TEXT
@@ -141,6 +138,39 @@ abort(){
 	exit 1
 	}
 	
+report_bug(){
+	datebug=`date '+%d•%m•%Y-%H•%M•%S'`
+	if [ -f $SYSDIR/build.prop ]; then
+	cp -pf $SYSDIR/build.prop $litegapps/log/sys_build.prop
+	fi
+
+	if [ -f $VENDIR/build.prop ]; then
+		cp -pf $VENDIR/build.prop $litegapps/log/ven_build.prop
+	fi
+
+	if [ -d $litegapps/log ]; then
+		listlog $tmp
+		listlog $MODPATH
+		listlog $litegapps
+		ls -alZR $MODPATH/system >> $loglive
+		cd $litegapps/log
+		$bin/busybox tar -cz -f $litegapps/litegapps_log_$datebug.tar.gz *
+		cd /
+		del $litegapps/log
+	fi
+	printlog " "
+	printlog "###########################"
+	printlog "# installation failed !!! #"
+	printlog "###########################"
+	printlog " known error •> $1"
+	printlog "###########################"
+	printlog " Please report bug !"
+	printlog " send log : /sdcard/Android/litegapps/litegapps_log_$datebug.tar.gz"
+	printlog " send in group telegram https://t.me/litegappsgroup"
+	printlog "############################"
+	printlog " "
+	exit 1
+}
 #
 del (){ rm -rf "$@"; }
 cdir (){ mkdir -p "$@"; }
